### ================================= AUTH ====================================== ###

### Register User (Public)
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "username": "shinkarow",
    "name": "Shinkarow",
    "email": "shinkarow7@gmail.com",
    "password": "admin123",
    "confirm_password": "admin123"
}

### Verify email
GET http://localhost:8080/api/v1/auth/verify-email?token=05565c21-e512-40fe-9e5c-998f0cce4976

### Resend Email Verifikasi
POST http://localhost:8080/api/v1/auth/resend-verification
Content-Type: application/json

{
    "email": "jatiedi54@gmail.com"
}

### Forgot Password
POST http://localhost:8080/api/v1/auth/forgot-password
Content-Type: application/json

{
    "email": "wadirestu09@gmail.com"
}

### Reset Password
POST http://localhost:8080/api/v1/auth/reset-password
Content-Type: application/json

{
    "token": "636039ae-a2e6-410e-9637-ee9a00e45ead",
    "new_password": "admin12345"
}

### Login (email or username)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "identifier": "superadmin",
    "password": "admin123"
}

### Refresh Token
POST http://localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
    "refreshToken": "<refresh-token>"
}

### Logout
POST http://localhost:8080/api/v1/auth/logout
Content-Type: application/json

{
    "refreshToken": "<refresh-token>"
}

### Create/Register new admin (admin only)
POST http://localhost:8080/api/v1/users/register
Authorization: Bearer <access-token>
Content-Type: application/json

{
    "username": "superadmin2",
    "name": "Admin Kedua",
    "email": "admin2@mail.com",
    "password": "admin123",
    "role": "admin"
}

### Promote User to Committee (admin only)
PATCH http://localhost:8080/api/v1/users/b9801e15-254a-4d79-a506-9fe75391b3c9/role
Authorization: Bearer <access-token>
Content-Type: application/json

{
    "role": "panitia"
}




### =========================== USERS ============================== ###

### Get All User (admin only)
GET http://localhost:8080/api/v1/users
Authorization: Bearer <access-token>

### Get User By ID (admin only)
GET http://localhost:8080/api/v1/users/{{ user_id }}
Authorization: Bearer <access-token>

### Get Own Profile
GET http://localhost:8080/api/v1/users/me
Authorization: Bearer <access-token>

### Update Profile
PUT http://localhost:8080/api/v1/users/{{ user_id }}
Authorization: Bearer <access-token>
Content-Type: application/json

{
    "username": "",
    "name": "",
    "email": ""
}

### Change Password
PUT http://localhost:8080/api/v1/users/07bd9d2e-6e33-4237-a262-d7dc67453336/password
Authorization: Bearer <access-token>
Content-Type: application/json

{
    "old_password": "admin123",
    "new_password": "admin12345",
    "confirm_password": "admin12345"
}

### DELETE USER (admin only)
DELETE http://localhost:8080/api/v1/users/07bd9d2e-6e33-4237-a262-d7dc67453336
Authorization: Bearer <access-token>




### ============================ PEKURBAN ============================= ###

### Create Pekurban (admin/panitia, user(only registered users are allowed to access))
POST http://localhost:8080/api/v1/pekurban
Authorization: Bearer <access-token>
Content-Type: application/json

{
    "user_id": "697b5711-5e19-4024-969a-d6304b28c1db",
    "name": "",
    "phone": "081234567899",
    "email": "",
    "alamat": "Jalan Raya Umum"
}

### Get All Pekurban (admin/panitia only)
GET http://localhost:8080/api/v1/pekurban
Authorization: Bearer <access-token>

### Get Pekurban by ID (admin/panitia only)
GET http://localhost:8080/api/v1/pekurban/ad7f0345-c119-4a52-9ab7-42922e04d8b0
Authorization: Bearer <access-token>

### Get Pekurban Me
GET http://localhost:8080/api/v1/pekurban/me
Authorization: Bearer <access-token>

### Update Pekurban 
PUT http://localhost:8080/api/v1/pekurban/53d2b555-4c8c-4e9d-8575-270ad4870553
Authorization: Bearer <access-token>
Content-Type: application/json

{
    "name": null,
    "phone": null,
    "email": null,
    "alamat": "Jl. Raya Umum, No. 123"
}

### Delete Pekurban (admin only)
DELETE http://localhost:8080/api/v1/pekurban/ad7f0345-c119-4a52-9ab7-42922e04d8b0
Authorization: Bearer <access-token>




### ====================== HEWAN KURBAN ======================== ###

### [ADMIN] Create Hewan Kurban
POST http://localhost:8080/api/v1/hewan-kurban
Authorization: Bearer <access-token>
Content-Type: application/json

{
    "jenis": "kambing",
    "berat": 20,
    "harga": 5000000,
    "is_private": false,
    "tanggal_pendaftaran": "2025-07-10"
}

### [ADMIN] Update Hewan Kurban
PUT http://localhost:8080/api/v1/hewan-kurban/7db4c831-684d-404b-956f-7db54d3e28fe
Authorization: Bearer <access-token>
Content-Type: application/json

{
    "berat": 509.25,
    "harga": 50000000,
    "is_private": false,
    "tanggal_pendaftaran": "2025-07-11"
}

### [ADMIN] Delete Hewan Kurban
DELETE http://localhost:8080/api/v1/hewan-kurban/482b7d21-6fec-4af4-aa74-e2f55680ca89
Authorization: Bearer <access-token>

### [ALL] Get All Hewan Kurban
GET http://localhost:8080/api/v1/hewan-kurban
Authorization: Bearer <access-token>

### [ALL] Get Hewan by ID
GET http://localhost:8080/api/v1/hewan-kurban/{{ hewan_kurban id }}
Authorization: Bearer <access-token>





### ====================== PEKURBAN HEWAN ======================== ###

### Create Patungan (Users can only manage their own Pekurban data, while admins and committee members are allowed to input data for any user.)
POST http://localhost:8080/api/v1/patungan
Authorization: Bearer <access-token>
Content-Type: application/json

{
    "pekurban_id": "d1202214-c807-43cb-ad13-5234f92537c6",
    "hewan_id": "204773f8-8001-4184-91fa-872e0b583f53",
    "jumlah_orang": 1
}

### Get All Patungan (admin/panitia only)
GET http://localhost:8080/api/v1/patungan
Authorization: Bearer <access-token>

### Get Patungan by Hewan (public)
GET http://localhost:8080/api/v1/patungan/hewan/{{ hewan_id }}
Authorization: Bearer <access-token>

### Get Patungan by Pekurban (public)
GET http://localhost:8080/api/v1/patungan/pekurban/{{ your_pekurban_id }}
Authorization: Bearer <access-token>

### Delete Patungan (only admin)
DELETE http://localhost:8080/api/v1/patungan/{{ pekurban_id }}/{{ hewan_id }}
Authorization: Bearer <access-token>





### ====================== PENYEMBELIHAN HEWAN ======================== ###

### Create penyembelihan (admin/panitia)
POST http://localhost:8080/api/v1/penyembelihan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTYWhhYmF0LUt1cmJhbiIsInN1YiI6ImI5ODAxZTE1LTI1NGEtNGQ3OS1hNTA2LTlmZTc1MzkxYjNjOSIsImV4cCI6MTc1Mjg2MTQyMiwiaWF0IjoxNzUyODYwMjIyLCJ1c2VyX2lkIjoiYjk4MDFlMTUtMjU0YS00ZDc5LWE1MDYtOWZlNzUzOTFiM2M5Iiwicm9sZSI6InBhbml0aWEifQ.k7ApEnFJJYm4WrBi3lNQJxL1npL9q3xUYprD8HiJ494
Content-Type: application/json

{
    "hewan_id": "204773f8-8001-4184-91fa-872e0b583f53",
    "tanggal_penyembelihan": "2025-07-15T09:00:00Z",
    "lokasi": "Masjid Al-Barokah",
    "urutan_rencana": 1
}

### Update penyembelihan (admin/panitia)
PUT http://localhost:8080/api/v1/penyembelihan/{{ penyembelihan_id }}
Authorization: Bearer <access-token>
Content-Type: application/json

{
    "tanggal_penyembelihan": "2025-07-15T10:00:00Z",
    "lokasi": "Lapangan RT 04",
    "urutan_rencana": 1,
    "urutan_aktual": 2
}

### Delete penyembelihan (admin only)
DELETE http://localhost:8080/api/v1/penyembelihan/{{ penyembelihan_id }}
Authorization: Bearer <access-token>

### Get all penyembelihan (all roles)
GET http://localhost:8080/api/v1/penyembelihan
Authorization: Bearer <access-token>

### Get penyembelihan by ID
GET http://localhost:8080/api/v1/penyembelihan/{{ penyembelihan_id }}
Authorization: Bearer <access-token>





### ========================== PENERIMA DAGING ============================ ###

### Create penerima (admin/panitia)
POST http://localhost:8080/api/v1/penerima
Authorization: Bearer <access-token>
Content-Type: application/json

{
    "name": "Septi Komala",
    "alamat": "Kp. Dukuh 2",
    "phone": "09888687986",
    "status": "warga",
    "pekurban_id": null
}

### Get all penerima daging (all roles)
GET http://localhost:8080/api/v1/penerima
Authorization: Bearer <access-token>

### Get by ID (all roles)
GET http://localhost:8080/api/v1/penerima/{{ user_id }}
Authorization: Bearer <access-token>

### Update penerima daging (admin/panitia)
PUT http://localhost:8080/api/v1/penerima/{{ user_id }}
Authorization: Bearer <access-token>
Content-Type: application/json

{
    "nama": null,
    "alamat": "Jalan Melati No.12 Blok B",
    "phone": null,
    "status": "pekurban",
    "pekurban_id": null
}

### Delete penerima daging (admin only)
DELETE http://localhost:8080/api/v1/penerima/{{ user_id }}
Authorization: Bearer <access-token>





### ============================== DISTRIBUSI DAGING ================================ ###

### Create distribusi daging (admin/panitia)
POST http://localhost:8080/api/v1/distribusi
Authorization: Bearer <access-token>
Content-Type: application/json

{
    "penerima_id": "{{ penerima_id }}",
    "hewan_id": "{{ hewan_id }}",
    "jumlah_paket": 1,
    "tanggal_distribusi": "2025-07-17"
}

### Get all distribusi (admin/panitia)
GET http://localhost:8080/api/v1/distribusi
Authorization: Bearer <access-token>

### Get total paket distribusi (admin/panitia)
GET http://localhost:8080/api/v1/distribusi/total-paket
Authorization: Bearer <access-token>

### Get belum terdistribusi (admin/panitia)
GET http://localhost:8080/api/v1/distribusi/belum-terdistribusi
Authorization: Bearer <access-token>

### Get distribusi by ID (admin/panitia)
GET http://localhost:8080/api/v1/distribusi/{{ distribusi_id }}
Authorization: Bearer <access-token>

### Delete distribusi (admin panitia)
DELETE http://localhost:8080/api/v1/distribusi/{{ distribusi_id }}
Authorization: Bearer <access-token>





### ============================ PEMBAYARAN KURBAN =============================== ###

# Create Pembayaran
POST http://localhost:8080/api/v1/pembayaran
Authorization: Bearer <access-token>
Content-Type: application/json

{
    "pekurban_id": "d1202214-c807-43cb-ad13-5234f92537c6",
    "metode": "bank_transfer",
    "bank": "bca"
}

###
# Get All Pembayaran
GET http://localhost:8080/api/v1/pembayaran
Authorization: Bearer <access-token>

###
# Get by ID
GET http://localhost:8080/api/v1/pembayaran/{{ pembayaran_id }}
Authorization: Bearer <access-token>

###
# Get by OrderID
GET http://localhost:8080/api/v1/pembayaran/order/ORDER-20250718-927def2a
Authorization: Bearer <access-token>

### Get rekap hewan
GET http://localhost:8080/api/v1/pembayaran/rekap/hewan
Authorization: Bearer <access-token>

### Get rekap pekurban
GET http://localhost:8080/api/v1/pembayaran/rekap/pekurban
Authorization: Bearer <access-token>

