### ================================= AUTH ====================================== ###

### Register User (Public)
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "username": "johndoel",
    "name": "John Doe",
    "email": "johndoe@gmail.com",
    "password": "admin123"
}

### Login (email or username)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "identifier": "<your email or username>",
    "password": ""
}

### Refresh Token
POST http://localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
    "refreshToken": "<your refresh token>"
}

### Logout
POST http://localhost:8080/api/v1/auth/logout
Content-Type: application/json

{
    "refreshToken": "<your refresh token>"
}

### Create/Register new admin (admin only)
POST http://localhost:8080/api/v1/users/register
Authorization: Bearer <your access token>
Content-Type: application/json

{
    "username": "superadmin2",
    "name": "Admin Kedua",
    "email": "admin2@mail.com",
    "password": "admin123",
    "role": "admin"
}

### Promote User to Committee (admin only)
PATCH http://localhost:8080/api/v1/users/{{ user_id }}/role
Authorization: Bearer <your access token>
Content-Type: application/json

{
    "role": "panitia"
}




### =========================== USERS ============================== ###

### Get All User (admin only)
GET http://localhost:8080/api/v1/users
Authorization: Bearer <your access token>

### Get User By ID (admin only)
GET http://localhost:8080/api/v1/users/{{ user_id }}
Authorization: Bearer <your access token>

### Get Own Profile
GET http://localhost:8080/api/v1/users/me
Authorization: Bearer <your access token>

### Update Profile
PUT http://localhost:8080/api/v1/users/{{ user_id }}
Authorization: Bearer <your access token>
Content-Type: application/json

{
    "username": "",
    "name": "",
    "email": ""
}

### Change Password
PUT http://localhost:8080/api/v1/users/{{ user_id }}/password
Authorization: Bearer <your access token>
Content-Type: application/json

{
    "old_password": "",
    "new_password": ""
}

### DELETE USER (admin only)
DELETE http://localhost:8080/api/v1/users/{{ user_id }}
Authorization: Bearer <your access token>




### ============================ PEKURBAN ============================= ###

### Create Pekurban (admin)
POST http://localhost:8080/api/v1/pekurban
Authorization: Bearer <your access token>
Content-Type: application/json

{
    "user_id": "<user id>",
    "name": "",
    "phone": "081234567856",
    "email": "",
    "alamat": "Jalan Raya Umum"
}

### Get All Pekurban (admin/panitia only)
GET http://localhost:8080/api/v1/pekurban
Authorization: Bearer <your access token>

### Get Pekurban by ID (admin/panitia only)
GET http://localhost:8080/api/v1/pekurban/{{ user_id }}
Authorization: Bearer <your access token>

### Update Pekurban 
PUT http://localhost:8080/api/v1/pekurban/{{ user_id }}
Authorization: Bearer <your access token>
Content-Type: application/json

{
    "name": "Ahmad Johndoe",
    "phone": "082222222233",
    "email": "johndoe@example.com",
    "alamat": "Dimana aja"
}

### Delete Pekurban (admin only)
DELETE http://localhost:8080/api/v1/pekurban/{{ user_id }}
Authorization: Bearer <your access token>





### ====================== HEWAN KURBAN ======================== ###

### [ADMIN] Create Hewan Kurban
POST http://localhost:8080/api/v1/hewan-kurban
Authorization: Bearer <your access token>
Content-Type: application/json

{
    "jenis": "sapi",
    "berat": 350.5,
    "tanggal_pendaftaran": "2025-07-10"
}

### [ADMIN] Update Hewan Kurban
PUT http://localhost:8080/api/v1/hewan-kurban/{{ hewan_kurban id }}
Authorization: Bearer <your access token>
Content-Type: application/json

{
    "berat": 410.25,
    "tanggal_pendaftaran": "2025-07-11"
}

### [ADMIN] Delete Hewan Kurban
DELETE http://localhost:8080/api/v1/hewan-kurban/{{ hewan_kurban id }}
Authorization: Bearer <your access token>

### [ALL] Get All Hewan Kurban
GET http://localhost:8080/api/v1/hewan-kurban
Authorization: Bearer <your access token>

### [ALL] Get Hewan by ID
GET http://localhost:8080/api/v1/hewan-kurban/{{ hewan_kurban id }}
Authorization: Bearer <your access token>
